#
# Makefile for padctrl support.
#
subdir-ccflags-y	= -Werror

obj-$(CONFIG_PADCTRL)			+= padctrl-core.o
obj-$(CONFIG_PADCTRL_TEGRA210_PMC)	+= padctrl-tegra210-pmc.o
obj-$(CONFIG_ARCH_OR_PLATFORM_TEGRA)	+= padctrl-tegra-io-pads.o
