obj-$(CONFIG_TEGRA124_EMC) += tegra124-emc.o

obj-$(CONFIG_TEGRA210_EMC) += t210-emc.o
t210-emc-objs += tegra210-emc.o tegra210-emc-cc-r21015.o tegra210-emc-cc-r21012.o tegra210-emc-cc-r21021.o tegra210-dt-parse.o

