#
# Makefile for tegra fuse support.
#
GCOV_PROFILE := y

subdir-ccflags-y       += -I$(srctree)/../t18x
subdir-ccflags-y       += -I$(srctree)

# subdir-ccflags-y	= -Werror
subdir-ccflags-y       += -I$(srctree)/../t18x
subdir-ccflags-y       += -I$(srctree)

obj-y	+= tegra_fuse.o
